# Generated by Django 2.0 on 2022-06-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='AGE',
        ),
        migrations.RemoveField(
            model_name='price',
            name='B',
        ),
        migrations.RemoveField(
            model_name='price',
            name='CHAS',
        ),
        migrations.RemoveField(
            model_name='price',
            name='DIS',
        ),
        migrations.RemoveField(
            model_name='price',
            name='INDUS',
        ),
        migrations.RemoveField(
            model_name='price',
            name='LSTAT',
        ),
        migrations.RemoveField(
            model_name='price',
            name='NOX',
        ),
        migrations.RemoveField(
            model_name='price',
            name='PTRATIO',
        ),
        migrations.RemoveField(
            model_name='price',
            name='RAD',
        ),
        migrations.RemoveField(
            model_name='price',
            name='RM',
        ),
        migrations.RemoveField(
            model_name='price',
            name='TAX',
        ),
        migrations.RemoveField(
            model_name='price',
            name='ZN',
        ),
    ]
