# Generated by Django 2.0 on 2022-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220623_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='AGE',
            field=models.FloatField(default=25),
        ),
    ]
