# Generated by Django 2.0 on 2022-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20220623_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='AGE',
            field=models.FloatField(default=0.0),
        ),
    ]
